version: 2

models:
  - name: dim_listings_cleansed
    description: table of cleansed dimension of listings.
    columns:

    - name: listing_id
      description: primary key of listings.
      tests:
        - unique
        - not_null

    - name: host_id
      description: foreign key from hosts.
      tests:
        - not_null
        - relationships:
            to: ref('dim_hosts_cleansed')
            field: host_id

    - name: room_type
      description: type of room.
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                    'Private room',
                    'Shared room',
                    'Hotel room']

    - name: minimum_nights
      description: duration of nights spent in the room.
      tests:
        - just_positive_values